apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- include "app.selectorLabels" (dict "name" "backend" "root" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "app.selectorLabels" (dict "name" "backend" "root" .) | nindent 4 }}
