{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "fastapi-oidc"
          serviceAccountRef:
            name: backend
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/fastapi-oidc/postgres
        property: password
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: secret/data/fastapi-oidc/keycloak
        property: admin_password
    - secretKey: GOOGLE_OIDC_CLIENT_SECRET
      remoteRef:
        key: secret/data/fastapi-oidc/google-oidc
        property: client_secret
{{- end }}
