{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" (dict "name" "backend" "root" .) | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" (dict "name" "frontend" "root" .) | nindent 6 }}
{{- end }}
