apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-oidc-app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ORG/fastapi-keycloak-envoy-oidc
    path: helm/fastapi-oidc-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-oidc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
